---
title: 'Milestone #2'
author: "Gabrielle Pesantez"
date: "9/25/2020"
output: html_document
---

__Repository URL:__ https://github.com/gabriellepesantez/milestone-2.git

__[Gun Violence Decrease in San Francisco and Oakland - Yao Yu](https://itsyaoyu.shinyapps.io/Gun_Violence_Bay_Area/)__

Yao's final project does an incredible job of walking viewers through a clear narrative. Each visualization is prefaced by well-supported explanations for why particular choices were made or why particular datasets were used. In addition, Yao provides a short, informational video at the end of his final project, again walking viewers through his decisions and also providing some key analysis on what viewers should be paying attention to in his visualizations. In his first "About" section, he details why he undertook the project, which provides viewers with a solid contextual grounding in the significance of this analysis. As Yao writes, this project was commissioned by March for Our Lives representatives who wanted to try to use this data to lower gun violence in the Bay Area and perhaps extrapolate out these findings to other communities in America. I think that including this information really helps engage whoever chooses to view this data.  I liked Yao's use of actual maps to illustrate the data on aggravated assault with guns in his areas of focus and I also really admired his use of animation here, which allows us to see changes over time within these maps. The visuals under "Violent Crime in Bay Area" were very interactive and user-friendly. I thought that separating out the graph by data from different years was a great way to allow people to analyze and understand the data on their own time. Additionally, Yao anticipates that viewers might have difficulty seeing a clear trend in the first visualization under this section, so he graphs his data per capita in order to clarify that trends do seem to exist in the other cities besides just Chicago. Another positive feature of this final project is that most of the visualizations include tags displaying the specific numerical y-value of a point, which seems like a useful addition for anyone curious about the exact values at play here. One thing that I would change is the presentation of the "Regression" section under the "Imprisonment and Gun Control Laws" section. Here, a linear regression seems very out of place for the San Francisco and Oakland graphs. Additionally, although the three different graphs displayed here use the same axis labels, it might be beneficial to separate the Gun Control Laws graph from the other two, as this would make the presentation of the data clearer.

__[Life in the Time of Coronavirus - Jessica Wu](https://jessicawu013.shinyapps.io/coronavirus/)__

I thought that the date specification on most of Jessica's visuals was a nice touch. Additionally, I thought that the idea of using Google Search trends was really interesting as a way of revealing a sense of the culture/sentiments of a particular moment in time. I think that Jessica's topic, which involved looking at COVID-19's effect on life, social relationships, and well-being, had an appeal in that it touched on both shared and drastically differing experiences during a pandemic. I appreciated her visual addressing domestic violence outbreaks during quarantine. I know that a rise in domestic violence has been more difficult to measure over the past few months, so the idea of looking into Google Search trends here is a really illuminating choice. Something that might be more helpful for future viewers would be a preliminary section with more background on what the project will be exploring and how it will do so. For her plots containing legends, it might be a good idea to reorder the legend so that it matches a top-down ordering of the lines displayed in the visual. Changing this order would make the legend and graphs a bit easier to read. For her section on "Sorrow," I wonder if there might have been a more cohesive way of displaying the data. While I liked her idea of using maps to uncover whether coronavirus cases were more prevalent in areas with higher Black populations, it can be difficult to analyze whether a trend exists when having to compare two really detailed maps with each other. While I think this works well for the New York-specific maps, the data shown in the full United States maps might be better off being shown in a plot, with racial demographics mapped to a color aesthetic.